apiVersion: v1
kind: Pod
metadata: 
  name: jupyter
spec:
  containers:
  - name: jupyter  
    image: nvcr.io/nvidia/pytorch:21.05-py3
    command: ["/bin/bash","-c","--"]
    args: ["while true; do sleep 1;done;"]
    resources:
      limits: 
        nvidia.com/gpu: 1      
  hostNetwork: true
