apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tensorflow-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage  # Must match the PV's storage class
