kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user-binding
  namespace: user1
subjects: 
- kind: User
  name: user1
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: UserRole
  apiGroup: ""
